endpoints metrics/measures + test
JStockwell/ISPP-G9-22-23 pull request #39
Opened 2023-03-12 13:51 UTC by alvaro-us

2023-03-12 17:13 UTC, Marioespiro requested changes
Actualmente los tests devuelven 8 errores y 3 fallos.

2023-03-13 20:28 UTC, mpadillatabuenca requested changes
te piden que devuelvas los nombres de las metricas que hay en la aplicacion
si en la aplicacion hay niveles de azucar, de globulos rojos y de oxigeno en sangre
tienes que devolver un json con esas 3 cosas, nada mas
las measures deben llevar fecha Y HORA

2023-03-14 12:21 UTC, mpadillatabuenca requested changes
Sigue sin funcionar, hay fallos al definir los métodos y las urls

2023-03-14 18:29 UTC, mpadillatabuenca approved these changes
Todo correcto, mergeando

2023-03-14 20:24 UTC, Marioespiro approved these changes
Aprobado miniño

2023-03-14 20:25 UTC, merged